### ISSUE TITLE
Survey staffing

### ISSUE THREAD

**Issue by sean-rohan-NOAA** [afsc-gap-products/EBS-Survey-Planning#33]

**Comment by NicoleCharriere-NOAA** [comment]
December
- [ ] Schedule meeting with Bering Sea Survey lead first week on January to discuss base sea days, any foreseen challenges, prioritization of known special project days, Chief Scientist/Deck Lead options, etc.
- [ ] Send message to both GOA-AI (Riggle) and Shellfish Assessment Survey Coordinators (Conrad) about beginning staffing process and include all coordinators in major decisions and meetings
- [ ] Review [GAP survey staffing form](https://docs.google.com/forms/d/1is7fyNTrx6GJnvqPk1AzyHalDNwn-pAPGxaYfsM-7Hw/edit)

January
- [ ]  Send out GAP survey staffing from in early January to all GAP staff who usually participate on survey. Deadline of 1 week.
- [ ] Set up bi-weekly meeting with all survey coordinators
- [ ] Begin crafting [staffing spreadsheet](https://docs.google.com/spreadsheets/d/1R2_80tTa0_QtLXM7_9zj_XVy8_3tLQE-6fuPorcvksw/edit#gid=1894369879) with dates/people based on Bering Sea Survey Lead guidelines and personnel availability
- [ ] Review [survey participant form](https://docs.google.com/forms/d/1TB_oMShqyS7TlFAibpfXYZ47K0o_-Awo06rCvm3U1_M/edit)
- [ ] Have Bering Sea Survey Lead and GOA-AI Survey Lead review participant form

February
- [ ] Email IPHC with survey dates in call for participation
- [ ] Email Food Habits supervisor (Hibpshman) for stomach collector participation
- [ ] Have RACE Division Director send out survey participant form to all AFSC division/program leads. Soft deadline of two weeks.
- [ ] Share initial staffing spreadsheet with all staffed participants and Bering Sea group and any respective supervisors
- [ ] Check with internal GAP cold water trainers (Anderson and Dowlin) for staffed personnel that need coldwater or medical refreshers
- [ ] Check in with RSST (Magner) about personal survey gear requests

March
- [ ] Have RACE Division Director send survey participant form across all science centers and partner organizations. Soft deadline of two weeks.
- [ ] Open form to volunteers after all FTEs are staffed. Soft deadline of two weeks.
- [ ] Update [RACE Surveys spreadsheet](https://docs.google.com/spreadsheets/d/1VFMjD0l-2t-MEm__exBYCvtiNmQGh81liK_HlB3YyEs/edit#gid=442853526) created by RACE Division Director, once roster is relatively stable and survey dates are known
- [ ] Begin on boarding process (cold water certification process, background checks, etc.) for volunteers
- [ ] Send out updated roster to all staffed personnel and any respective supervisors
- [ ] Send out [dietary restriction form](https://drive.google.com/drive/folders/1SK7aUUipRs3a__IxoV0pBRgliCsSFHJH)
- [ ] Email RSST (Magner) about sea bag due date
- [ ] Send out email to all staff participants about sea bag due date, including IPHC
- [ ] Send RSST (Magner) updated roster for survival suits
- [ ] Send email to RACE Deputy Director, if observers needed for survey
- [ ] Send aggregated dietary restrictions to Vessel Coordinator (Hoff)
- [ ] Email IPHC regarding shipment of sampling equipment to AFSC, Seattle to load in survey shipping containers

April
- [ ] Send out employee work schedule form for change of hours effective between pay periods of travel
- [ ] Ensure dietary restrictions (sent to Hoff) and survival suit information (sent to Magner) for volunteers is captured and communicated
- [ ] Send out any staffing schedule updates
- [ ] Email reminder of sea bag due date

May
- [ ] Send out any staffing schedule updates
- [ ] Send out email with Google folder containing emergency medical forms (and remind people to have two sealed copies - one for supervisor, one for vessel) and travel document forms (Comp Time, Tax Exempt Form, Tax Exempt Rental Car, and Travel Voucher Form)
