### ISSUE TITLE
Overtime Authorization

### ISSUE THREAD

**Issue by sean-rohan-NOAA** [afsc-gap-products/EBS-Survey-Planning#36]

**Comment by NicoleCharriere-NOAA** [comment]
- [ ] Create [overtime calculation calendar](https://docs.google.com/spreadsheets/d/1fYI0JZlroLe1PEmSlAtOQXJdE2lz_6VAj4hTkWHDC4A/edit#gid=0) using assumption of 13 working hours per sea day and 10 hrs per setup day
- [ ] Create "OT Authorizations" folder in shared Groundfish drive under "EBSother" and EBScurrent year
- [ ] Create "Unsigned OT Forms" folder for Bering Sea Survey Lead
- [ ] Create "Signed OT Forms" folder for RACE Division Director
- [ ] Insert OT calculations on US Department of Commerce Form CD-81 for all FTEs on a by-leg and by-pay-period basis
- [ ] Place unsigned OT forms in designated folder for Bering Sea Survey Lead and email Bering Sea Survey Lead once complete
- [ ] All OT forms signed by Bering Sea Survey Lead
- [ ] Place signed OT forms in designated folder for RACE Division Director and email RACE Division Director once complete
- [ ] All OT forms signed by RACE Division Director
- [ ] OT forms sent to admin by RACE Division Director
